doctype html
html
  head
    title PixeLBot
    link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"

    css:
      html, body {
        background: black;
        color: white;
        font-family: 'roboto';
        text-align: center;
      }

  body
    h1 PixeLBot
    hr

    h3 Link your account
    p Please link your Discord account so we can get started with linking your Minecraft account.
    a href="#{authorize_url}" Click here to get started!



